const mongoose = require('mongoose');

const LogSchema = new mongoose.Schema({
  origin: { type: String, required: true }, // app/origin name or URL (causing logs)
  level: { type: String, default: 'info' }, //Log severity level (info, warning, error, debug, etc.)
  message: { type: String, required: true }, //log message
  meta: { type: mongoose.Schema.Types.Mixed }, // arbitrary JSON
  timestamp: { type: Date, default: Date.now },
  processed: { type: Boolean, default: false }, //worker processed it or not
  summary: { type: String }, //summary generated by AI
  groupId: { type: mongoose.Schema.Types.ObjectId, ref: 'Group' } // err associated with one group
}, {
  timestamps: true
});

module.exports = mongoose.model('Logs' , LogSchema);